package view;

import java.awt.EventQueue;

/**
 *
 * @author Santiago Palacio Vásquez
 */
public class LoginView extends javax.swing.JFrame {

    private final LoginPanel loginPanel;
    private final RegisterPanel registerPanel;

    public LoginView() {
        loginPanel = new LoginPanel(this);
        registerPanel = new RegisterPanel(this);

        initComponents();
        setResizable(false);
        add(loginPanel);
        add(registerPanel);
        showLoginPanel();

        setVisible(true);
    }

    public void showLoginPanel() {
        setTitle("Login");
        setSize(400, 300);
        setLocationRelativeTo(null);

        loginPanel.setVisible(true);
        registerPanel.setVisible(false);
    }

    public void showRegisterPanel(String email, String password) {
        setTitle("Register");
        setSize(400, 500);
        setLocationRelativeTo(null);

        loginPanel.setVisible(false);
        registerPanel.setEmail(email);
        registerPanel.setPassword(password);
        registerPanel.setVisible(true);
    }

    public void showMainView() {
        dispose();
        EventQueue.invokeLater(MainView::new);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pack();
    } // </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
