package view;

import java.awt.Dimension;
import java.awt.EventQueue;

public class MainView extends javax.swing.JFrame {

    public MainView() {
        initComponents();
        setTitle("Library Management");
        setMinimumSize(new Dimension(1111, 800));
        setPreferredSize(new Dimension(1280, 800));
        setSize(getPreferredSize());
        setLocationRelativeTo(null);

        tbpMain.addTab("Users", new UsersPanel(this));
        tbpMain.addTab("Books", new BooksPanel());
        tbpMain.addTab("My Books", new BorrowedBooks());
        tbpMain.addTab("Book Genres", new BookGenresPanel());
        tbpMain.addTab("Transactions", new TransactionsPanel());
        tbpMain.addTab("Reports", new ReportsPanel());

        setVisible(true);
    }

    public void logout() {
        dispose();
        EventQueue.invokeLater(LoginView::new);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        tbpMain = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tbpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tbpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tbpMain;
    // End of variables declaration//GEN-END:variables
}
