package view;

import controller.UserController;
import java.awt.event.ActionEvent;
import util.Message;

/**
 *
 * @author Santiago Palacio Vásquez
 */
public class LoginPanel extends javax.swing.JPanel {

  private final LoginView loginView;
  private final UserController userController;

  public LoginPanel(LoginView loginView) {
    this.loginView = loginView;
    userController = UserController.getInstance();

    initComponents();
    initListeners();
  }

  private void initListeners() {
    btnLogin.addActionListener(this::login);
    btnRegister.addActionListener(this::register);
  }

  private void login(ActionEvent evt) {
    if (getEmail().isEmpty() || getPassword().isEmpty()) {
      Message.showWarningMessage(this, "Fill all the fields");
      return;
    }
    try {
      userController.login(getEmail(), getPassword());
      loginView.showMainView();
    } catch (Exception e) {
      Message.showErrorMessage(this, e.getMessage());
    }
  }

  private void register(ActionEvent evt) {
    loginView.showRegisterPanel(getEmail(), getPassword());
  }

  public void clearFields() {
    txtId.setText("");
    password.setText("");
  }

  public String getEmail() {
    return txtId.getText().trim();
  }

  public String getPassword() {
    return String.valueOf(password.getPassword());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    lbl6 = new javax.swing.JLabel();
    lbl7 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    password = new javax.swing.JPasswordField();

    lbl6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    lbl6.setText("email");

    txtId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

    lbl7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    lbl7.setText("password");

    jPanel3.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

    btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    btnRegister.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/resources/register.png")
      )
    ); // NOI18N
    btnRegister.setText("Register");
    btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRegister.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
    jPanel3.add(btnRegister);

    btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    btnLogin.setIcon(
      new javax.swing.ImageIcon(getClass().getResource("/resources/login.png"))
    ); // NOI18N
    btnLogin.setText("Login");
    btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
    jPanel3.add(btnLogin);

    password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtId)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(lbl6)
                        .addComponent(lbl7)
                    )
                    .addGap(0, 0, Short.MAX_VALUE)
                )
                .addComponent(
                  jPanel3,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  288,
                  Short.MAX_VALUE
                )
                .addComponent(
                  password,
                  javax.swing.GroupLayout.Alignment.TRAILING
                )
            )
            .addContainerGap()
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              txtId,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbl7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              password,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(
              jPanel3,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              40,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private final javax.swing.JButton btnLogin = new javax.swing.JButton();
  private final javax.swing.JButton btnRegister = new javax.swing.JButton();
  private javax.swing.JPanel jPanel3;
  private javax.swing.JLabel lbl6;
  private javax.swing.JLabel lbl7;
  private javax.swing.JPasswordField password;
  private final javax.swing.JTextField txtId = new javax.swing.JTextField();
  // End of variables declaration//GEN-END:variables
}
