package view;

import controller.UserController;
import java.awt.EventQueue;
import java.sql.SQLException;
import java.util.Arrays;
import model.Role;
import util.Message;

/**
 *
 * @author Santiago Palacio Vásquez
 */
public class RegisterPanel extends javax.swing.JPanel {

  private LoginView loginView;
  private UserController userController;

  public RegisterPanel(LoginView loginView) {
    this.loginView = loginView;
    userController = UserController.getInstance();

    initComponents();
    initListeners();
  }

  private void initListeners() {
    btnRegister.addActionListener(this::register);
    btnCancel.addActionListener(this::cancel);
  }

  private void register(java.awt.event.ActionEvent evt) {
    if (
      txtId.getText().trim().isEmpty() ||
      password.getPassword().length == 0 ||
      txtFirstname.getText().trim().isEmpty() ||
      txtLastname.getText().trim().isEmpty()
    ) {
      Message.showWarningMessage(this, "Fill all the fields");
      return;
    }
    try {
      userController.register(
        txtId.getText().trim(),
        String.valueOf(password.getPassword()),
        txtFirstname.getText().trim(),
        txtLastname.getText().trim(),
        Role.USER
      );
      loginView.showMainView();
    } catch (Exception e) {
      Message.showErrorMessage(this, e.getMessage());
    }
  }

  public void setEmail(String email) {
    txtId.setText(email);
  }

  public void setPassword(String password) {
    this.password.setText(password);
  }

  private void cancel(java.awt.event.ActionEvent evt) {
    loginView.showLoginPanel();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    lbl5 = new javax.swing.JLabel();
    lbl4 = new javax.swing.JLabel();
    lbl6 = new javax.swing.JLabel();
    lbl7 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    password = new javax.swing.JPasswordField();

    lbl5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    lbl5.setText("email");

    txtId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

    lbl4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    lbl4.setText("password");

    lbl6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    lbl6.setText("first name");

    txtFirstname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

    lbl7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    lbl7.setText("last name");

    txtLastname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

    jPanel3.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

    btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    btnCancel.setIcon(
      new javax.swing.ImageIcon(getClass().getResource("/resources/update.png"))
    ); // NOI18N
    btnCancel.setText("Cancel");
    btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
    jPanel3.add(btnCancel);

    btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    btnRegister.setIcon(
      new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))
    ); // NOI18N
    btnRegister.setText("Register");
    btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnRegister.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
    jPanel3.add(btnRegister);

    password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(password)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(lbl5)
                        .addComponent(lbl4)
                    )
                    .addGap(0, 0, Short.MAX_VALUE)
                )
                .addComponent(txtId)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGroup(
                      layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(lbl6)
                        .addComponent(lbl7)
                    )
                    .addGap(218, 218, 218)
                )
                .addComponent(txtFirstname)
                .addComponent(txtLastname)
                .addComponent(
                  jPanel3,
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addContainerGap()
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              txtId,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(lbl4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              password,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(lbl6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              txtFirstname,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(lbl7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              txtLastname,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(
              jPanel3,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              40,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private final javax.swing.JButton btnCancel = new javax.swing.JButton();
  private final javax.swing.JButton btnRegister = new javax.swing.JButton();
  private javax.swing.JPanel jPanel3;
  private javax.swing.JLabel lbl4;
  private javax.swing.JLabel lbl5;
  private javax.swing.JLabel lbl6;
  private javax.swing.JLabel lbl7;
  private javax.swing.JPasswordField password;
  private final javax.swing.JTextField txtFirstname = new javax.swing.JTextField();
  private final javax.swing.JTextField txtId = new javax.swing.JTextField();
  private final javax.swing.JTextField txtLastname = new javax.swing.JTextField();
  // End of variables declaration//GEN-END:variables
}
