/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exam2;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.EventQueue;
import view.MainFrame;

public class App {

    public static void main(String[] args) {
        FlatMacDarkLaf.setup();
        EventQueue.invokeLater(MainFrame::new);
    }
}
